import HeroSection from "@/components/sections/HeroSection/HeroSection";
import StepsSection from "@/components/sections/StepsSection/StepsSection";
import ServicesPreview from "@/features/services/ui/ServicesPreview/ServicesPreview";
import FaqSection from "@/components/sections/FaqSection/FaqSection";
import ProjectsPreview from "@/features/projects/ui/ProjectsPreview/ProjectsPreview";
import CtaSection from "@/components/sections/CtaSection/CtaSection";
import BlogPreview from "@/features/blog/ui/BlogPreview/BlogPreview";

export default async function Home() {
  return (
    <div className="relative">
      <HeroSection />
      <StepsSection />
      <ServicesPreview />
      <ProjectsPreview />
      {/* <BlogPreview /> */}
      {/* <FaqSection /> */}
      {/* <CtaSection /> */}
    </div>
  );
}

// const MOCK_PROJECTS: Project[] = [
//   {
//     _id: "1",
//     title: "Radiant Skincare E-commerce Platform",
//     description: "Разработка высоконагруженной e-commerce платформы для бренда ухода за кожей",
//     fullDescription: "Разработка полнофункциональной e-commerce платформы на стеке MERN (MongoDB, Express, React, Node.js) для бренда Radiant Skincare. Реализованы персонализированные рекомендации на основе ИИ, система управления контентом, интеграция с платежными системами и аналитика в реальном времени.",
//     category: "software-development",
//     tags: ["ВЕБ-РАЗРАБОТКА", "E-COMMERCE", "ИИ", "БЭКЕНД"],
//     image: "/images/content/test.jpg",
//     slug: "radiant-skincare-platform",
//     client: "Radiant Skincare",
//     duration: "3 месяца",
//     technologies: ["React", "Node.js", "MongoDB", "AWS", "TensorFlow.js", "Stripe API"],
//     challenges: ["Обработка более 10,000 одновременных пользователей", "Интеграция системы рекомендаций на основе машинного обучения", "Обеспечение безопасности платежных данных"],
//     solutions: ["Микросервисная архитектура с балансировкой нагрузки", "Внедрение алгоритмов машинного обучения для персонализации", "Реализация end-to-end шифрования и PCI DSS compliance"],
//     results: ["Снижение времени загрузки страниц на 60%", "Увеличение конверсии на 40% за счет персонализации", "Обработка 50,000+ заказов в месяц без сбоев"],
//     createdAt: "2024-01-01",
//     updatedAt: "2024-01-01",
//   },
//   {
//     _id: "2",
//     title: "Apex Clothing ERP System",
//     description: "Внедрение корпоративной ERP системы для сети одежды",
//     fullDescription: "Разработка и внедрение корпоративной системы управления ресурсами (ERP) для бренда одежды Apex Clothing. Система объединила управление инвентарем, логистику, CRM и аналитику в единую платформу с мобильным приложением для сотрудников.",
//     category: "web-development",
//     tags: ["ERP", "CRM", "MOBILE", "CLOUD"],
//     image: "/images/content/test2.jpg",
//     slug: "apex-clothing-erp",
//     client: "Apex Clothing Co.",
//     duration: "4 месяца",
//     technologies: ["Java Spring Boot", "PostgreSQL", "React Native", "Kubernetes", "Azure"],
//     challenges: ["Интеграция с 5 различными legacy системами", "Обеспечение работы в оффлайн-режиме для мобильных сотрудников", "Масштабирование под 200+ магазинов сети"],
//     solutions: ["REST API Gateway для интеграции со сторонними системами", "PWA-приложение с оффлайн-хранилищем", "Контейнеризация и автоматическое масштабирование в облаке"],
//     results: ["Сокращение времени обработки заказов на 70%", "Автоматизация 80% рутинных операций", "Единая система данных для всех подразделений"],
//     createdAt: "2024-01-01",
//     updatedAt: "2024-01-01",
//   },
//   {
//     _id: "3",
//     title: "Vero Social Media AI Moderation",
//     description: "Внедрение системы модерации контента на базе ИИ",
//     fullDescription: "Разработка и внедрение системы автоматической модерации пользовательского контента для социальной сети Vero. Система использует компьютерное зрение и NLP для обнаружения нежелательного контента, спама и нарушений правил сообщества.",
//     category: "ai-integration",
//     tags: ["ИИ", "NLP", "CV", "МОДЕРАЦИЯ"],
//     image: "/images/content/test3.jpg",
//     slug: "vero-ai-moderation",
//     client: "Vero Social Media",
//     duration: "6 месяцев",
//     technologies: ["Python", "TensorFlow", "OpenCV", "FastAPI", "Redis", "Docker"],
//     challenges: ["Обработка 1+ млн изображений и видео ежедневно", "Минимизация ложных срабатываний", "Адаптация под различные культурные контексты"],
//     solutions: ["Ансамбль нейросетевых моделей для разных типов контента", "Система активного обучения с участием модераторов", "Мультиязычная NLP-модель для текстовой модерации"],
//     results: ["Автоматизация 95% процессов модерации", "Снижение времени реакции на нарушения с часов до минут", "Сокращение команды модераторов на 70%"],
//     createdAt: "2024-01-01",
//     updatedAt: "2024-01-01",
//   },
//   {
//     _id: "4",
//     title: "Stoyo Supply Chain Optimization",
//     description: "Оптимизация цепочки поставок с помощью IoT и аналитики",
//     fullDescription: "Разработка IoT-платформы для мониторинга и оптимизации цепочки поставок производителя йогуртов Stoyo. Система включает датчики температуры, отслеживание транспорта в реальном времени и предиктивную аналитику для управления запасами.",
//     category: "telephony",
//     tags: ["IoT", "АНАЛИТИКА", "BIG DATA", "REAL-TIME"],
//     image: "/images/content/test4.jpg",
//     slug: "stoyo-supply-chain",
//     client: "Stoyo Foods",
//     duration: "2 месяца",
//     technologies: ["Node.js", "MQTT", "InfluxDB", "Grafana", "React", "AWS IoT Core"],
//     challenges: ["Мониторинг температуры в 500+ холодильных установках", "Интеграция данных с 30+ логистических партнеров", "Прогнозирование спроса с точностью 90%+"],
//     solutions: ["Распределенная сеть IoT-датчиков с LoRaWAN", "Единая платформа данных с API для интеграций", "Машинное обучение для прогнозирования спроса"],
//     results: ["Сокращение потерь продукции на 45%", "Улучшение точности прогнозов до 92%", "Автоматическое оповещение о нарушениях температурного режима"],
//     createdAt: "2024-01-01",
//     updatedAt: "2024-01-01",
//   },
//   {
//     _id: "5",
//     title: "Timeless Impressions Cloud Migration",
//     description: "Миграция монолитного приложения в облачную микросервисную архитектуру",
//     fullDescription: "Полная миграция монолитного e-commerce приложения Timeless Impressions из локального дата-центра в облако AWS с переходом на микросервисную архитектуру. Проект включал рефакторинг, контейнеризацию и внедрение CI/CD.",
//     category: "devops",
//     tags: ["CLOUD", "MICROSERVICES", "CI/CD", "MIGRATION"],
//     image: "/images/content/test5.jpg",
//     slug: "timeless-cloud-migration",
//     client: "Timeless Impressions",
//     duration: "5 месяцев",
//     technologies: ["AWS", "Kubernetes", "Docker", "Terraform", "GitLab CI", "TypeScript"],
//     challenges: ["Миграция без простоев работающего продакшена", "Переобучение команды разработки", "Обеспечение backward compatibility"],
//     solutions: ["Стратегия blue-green deployment", "Поэтапный рефакторинг с feature flags", "Полная документация и воркшопы для команды"],
//     results: ["Снижение затрат на инфраструктуру на 40%", "Ускорение деплоя с дней до минут", "100% доступность во время миграции"],
//     createdAt: "2024-01-01",
//     updatedAt: "2024-01-01",
//   },
//   {
//     _id: "6",
//     title: "FinTech Banking App",
//     description: "Разработка мобильного банкинга с биометрической аутентификацией",
//     fullDescription: "Создание нативного мобильного приложения для банка с поддержкой биометрической аутентификации, бесконтактных платежей и финансовых советников на базе ИИ.",
//     category: "software-development",
//     tags: ["MOBILE", "FINTECH", "SECURITY", "AI"],
//     image: "",
//     slug: "fintech-banking-app",
//     client: "Global Trust Bank",
//     duration: "5 месяцев",
//     technologies: ["Swift", "Kotlin", "React Native", "Firebase", "Face ID API", "Apple Pay"],
//     challenges: ["Соответствие стандартам PCI DSS и GDPR", "Реализация оффлайн-режима", "Поддержка 10+ валют"],
//     solutions: ["Шифрование данных end-to-end", "Синхронизация при восстановлении соединения", "Мультивалютный движок с реальными курсами"],
//     results: ["Снижение мошеннических операций на 75%", "Увеличение активных пользователей на 120%", "Рейтинг 4.8+ в App Store и Google Play"],
//     createdAt: "2024-02-15",
//     updatedAt: "2024-02-15",
//   },
//   {
//     _id: "7",
//     title: "Healthcare Telemedicine Platform",
//     description: "Платформа телемедицины для сети клиник",
//     fullDescription: "Разработка комплексной платформы телемедицины, включающей видеоконсультации, электронные медкарты, онлайн-запись и интеграцию с медицинским оборудованием.",
//     category: "telephony",
//     tags: ["HEALTHCARE", "TELEMEDICINE", "VIDEO", "SECURITY"],
//     image: "",
//     slug: "healthcare-telemedicine-platform",
//     client: "MediCare Network",
//     duration: "6 месяцев",
//     technologies: ["WebRTC", "Node.js", "MongoDB", "React", "HIPAA Compliance", "AWS"],
//     challenges: ["Обеспечение конфиденциальности медицинских данных", "Стабильная видео-связь при низком интернете", "Интеграция с 20+ видами медоборудования"],
//     solutions: ["Сертификация HIPAA и GDPR", "Адаптивное качество видео", "Универсальный API для интеграции"],
//     results: ["Увеличение охвата пациентов на 300%", "Сокращение времени ожидания приема с 3 дней до 30 минут", "Автоматизация 60% административных задач"],
//     createdAt: "2024-03-10",
//     updatedAt: "2024-03-10",
//   },
//   {
//     _id: "8",
//     title: "Smart City Traffic Management",
//     description: "Система управления городским трафиком на базе ИИ",
//     fullDescription: "Внедрение интеллектуальной системы управления дорожным движением, использующей камеры, датчики и машинное обучение для оптимизации светофоров и уменьшения пробок.",
//     category: "ai-integration",
//     tags: ["SMART CITY", "AI", "IoT", "REAL-TIME"],
//     image: "",
//     slug: "smart-city-traffic-management",
//     client: "City Municipal Government",
//     duration: "8 месяцев",
//     technologies: ["Python", "TensorFlow", "Apache Kafka", "Docker", "AWS IoT", "Redis"],
//     challenges: ["Обработка данных с 500+ камер в реальном времени", "Прогнозирование трафика в праздничные дни", "Интеграция с существующей инфраструктурой"],
//     solutions: ["Распределенная обработка видео", "Прогнозные модели на основе исторических данных", "REST API для интеграции с городскими системами"],
//     results: ["Снижение пробок на 35%", "Уменьшение времени в пути на 25%", "Сокращение ДТП на 40%"],
//     createdAt: "2024-04-05",
//     updatedAt: "2024-04-05",
//   },
//   {
//     _id: "9",
//     title: "EdTech Learning Platform",
//     description: "Интерактивная образовательная платформа для школ",
//     fullDescription: "Создание платформы для дистанционного обучения с интерактивными уроками, автоматической проверкой заданий и адаптивным обучением.",
//     category: "software-development",
//     tags: ["EDTECH", "EDUCATION", "LMS", "GAMIFICATION"],
//     image: "",
//     slug: "edtech-learning-platform",
//     client: "EduFuture Schools",
//     duration: "4 месяца",
//     technologies: ["React", "Node.js", "MongoDB", "WebSockets", "Canvas API", "LTI"],
//     challenges: ["Поддержка 10,000+ одновременных пользователей", "Создание интерактивных упражнений", "Интеграция с школьными системами"],
//     solutions: ["Микросервисная архитектура", "Конструктор интерактивных заданий", "Стандарт LTI для интеграции"],
//     results: ["Улучшение успеваемости на 28%", "Увеличение вовлеченности студентов на 65%", "Внедрение в 200+ школ"],
//     createdAt: "2024-05-20",
//     updatedAt: "2024-05-20",
//   },
//   {
//     _id: "10",
//     title: "Retail Analytics Dashboard",
//     description: "Дашборд аналитики для розничной сети",
//     fullDescription: "Разработка BI-панели для анализа продаж, трафика в магазинах и эффективности маркетинговых кампаний в реальном времени.",
//     category: "ai-integration",
//     tags: ["BI", "ANALYTICS", "RETAIL", "REAL-TIME"],
//     image: "",
//     slug: "retail-analytics-dashboard",
//     client: "MegaRetail Chain",
//     duration: "3 месяца",
//     technologies: ["React", "D3.js", "Python", "PostgreSQL", "Apache Superset", "Redis"],
//     challenges: ["Агрегация данных из 15+ источников", "Обновление данных в реальном времени", "Создание интуитивных визуализаций"],
//     solutions: ["Data pipeline на Apache Airflow", "WebSocket для real-time обновлений", "Кастомные графики на D3.js"],
//     results: ["Увеличение среднего чека на 15%", "Сокращение излишков инвентаря на 30%", "Экономия $2M+ на маркетинге"],
//     createdAt: "2024-06-15",
//     updatedAt: "2024-06-15",
//   },
//   {
//     _id: "11",
//     title: "Blockchain Supply Chain",
//     description: "Блокчейн-платформа для отслеживания цепочек поставок",
//     fullDescription: "Создание прозрачной системы отслеживания товаров от производителя к потребителю с использованием блокчейн-технологии.",
//     category: "software-development",
//     tags: ["BLOCKCHAIN", "SUPPLY CHAIN", "TRANSPARENCY", "SMART CONTRACTS"],
//     image: "",
//     slug: "blockchain-supply-chain",
//     client: "Global Logistics Inc.",
//     duration: "7 месяцев",
//     technologies: ["Ethereum", "Solidity", "Node.js", "React", "IPFS", "Web3.js"],
//     challenges: ["Масштабирование блокчейн-сети", "Интеграция с существующими ERP", "Обучение персонала"],
//     solutions: ["Layer 2 решение на Polygon", "REST API для интеграции", "Интерактивные туториалы"],
//     results: ["Сокращение бумажного документооборота на 90%", "Повышение доверия клиентов на 60%", "Снижение фальсификаций на 95%"],
//     createdAt: "2024-07-01",
//     updatedAt: "2024-07-01",
//   },
//   {
//     _id: "12",
//     title: "AR Furniture Application",
//     description: "AR-приложение для виртуальной примерки мебели",
//     fullDescription: "Разработка мобильного приложения с дополненной реальностью для визуализации мебели в интерьере перед покупкой.",
//     category: "software-development",
//     tags: ["AR", "MOBILE", "3D", "E-COMMERCE"],
//     image: "",
//     slug: "ar-furniture-application",
//     client: "HomeStyle Furniture",
//     duration: "4 месяца",
//     technologies: ["Unity", "ARKit", "ARCore", "React Native", "Firebase", "Blender"],
//     challenges: ["Точное позиционирование 3D-моделей", "Оптимизация для мобильных устройств", "Создание реалистичных материалов"],
//     solutions: ["SLAM-алгоритмы для позиционирования", "LOD системы для оптимизации", "PBR материалы для реализма"],
//     results: ["Увеличение конверсии на 45%", "Снижение возвратов на 70%", "Рост среднего чека на 30%"],
//     createdAt: "2024-08-10",
//     updatedAt: "2024-08-10",
//   },
//   {
//     _id: "13",
//     title: "Cybersecurity Monitoring System",
//     description: "Система мониторинга кибербезопасности для банка",
//     fullDescription: "Разработка системы обнаружения и предотвращения кибератак в реальном времени для финансового учреждения.",
//     category: "it-audit",
//     tags: ["SECURITY", "MONITORING", "REAL-TIME", "FINANCE"],
//     image: "",
//     slug: "cybersecurity-monitoring-system",
//     client: "SecureBank",
//     duration: "6 месяцев",
//     technologies: ["Python", "Elasticsearch", "Kibana", "Docker", "ML", "SIEM"],
//     challenges: ["Обработка 1TB+ логов ежедневно", "Минимизация ложных срабатываний", "Соответствие регуляторным требованиям"],
//     solutions: ["ML-модели для аномалий", "Правила корреляции событий", "Автоматические отчеты для регуляторов"],
//     results: ["Обнаружение 99.9% угроз", "Сокращение времени реакции с часов до минут", "Соответствие PCI DSS и ISO 27001"],
//     createdAt: "2024-09-05",
//     updatedAt: "2024-09-05",
//   },
//   {
//     _id: "14",
//     title: "Green Energy Management",
//     description: "Платформа управления возобновляемыми источниками энергии",
//     fullDescription: "Система для мониторинга и оптимизации работы солнечных панелей и ветрогенераторов в умных городах.",
//     category: "web-development",
//     tags: ["IOT", "GREEN ENERGY", "SMART GRID", "ANALYTICS"],
//     image: "",
//     slug: "green-energy-management",
//     client: "EcoPower Solutions",
//     duration: "5 месяцев",
//     technologies: ["Node.js", "MQTT", "InfluxDB", "Grafana", "React", "Python"],
//     challenges: ["Интеграция с различными типами оборудования", "Прогнозирование выработки энергии", "Балансировка нагрузки сети"],
//     solutions: ["Универсальный протокол для устройств", "ML-модели прогнозирования", "Алгоритмы балансировки нагрузки"],
//     results: ["Увеличение эффективности на 25%", "Снижение потерь энергии на 15%", "Автоматизация управления сетью"],
//     createdAt: "2024-10-01",
//     updatedAt: "2024-10-01",
//   },
//   {
//     _id: "15",
//     title: "Gaming Tournament Platform",
//     description: "Платформа для проведения киберспортивных турниров",
//     fullDescription: "Создание платформы для организации и проведения онлайн-турниров с системой регистрации, стримингом и автоматическими выплатами.",
//     category: "software-development",
//     tags: ["GAMING", "ESPORTS", "STREAMING", "PAYMENTS"],
//     image: "",
//     slug: "gaming-tournament-platform",
//     client: "GamePro Esports",
//     duration: "4 месяца",
//     technologies: ["React", "Node.js", "WebSockets", "WebRTC", "Stripe", "Docker"],
//     challenges: ["Поддержка 50,000+ зрителей", "Защита от читов", "Мгновенные выплаты призеров"],
//     solutions: ["CDN для стримов", "Античит система", "Интеграция с платежными системами"],
//     results: ["Проведение 100+ турниров ежемесячно", "Аудитория 500,000+ зрителей", "Автоматические выплаты за 5 минут"],
//     createdAt: "2024-10-20",
//     updatedAt: "2024-10-20",
//   },
//   {
//     _id: "16",
//     title: "Legal Document Automation",
//     description: "Система автоматизации составления юридических документов",
//     fullDescription: "AI-платформа для автоматического составления договоров, соглашений и других юридических документов.",
//     category: "ai-integration",
//     tags: ["AI", "LEGAL", "AUTOMATION", "NLP"],
//     image: "",
//     slug: "legal-document-automation",
//     client: "LawTech Partners",
//     duration: "6 месяцев",
//     technologies: ["Python", "FastAPI", "GPT-4", "React", "PostgreSQL", "Docker"],
//     challenges: ["Точность юридических формулировок", "Поддержка различных юрисдикций", "Конфиденциальность данных"],
//     solutions: ["Fine-tuning LLM на юридических текстах", "База шаблонов для юрисдикций", "End-to-end шифрование"],
//     results: ["Сокращение времени составления документов на 90%", "Уменьшение ошибок на 95%", "Экономия $1.5M на юридических услугах"],
//     createdAt: "2024-11-01",
//     updatedAt: "2024-11-01",
//   },
//   {
//     _id: "17",
//     title: "Real Estate Virtual Tours",
//     description: "Платформа для виртуальных туров по недвижимости",
//     fullDescription: "Создание системы 360° виртуальных туров с возможностью измерений и онлайн-просмотров.",
//     category: "video-surveillance",
//     tags: ["VR", "REAL ESTATE", "3D", "IMMERSIVE"],
//     image: "",
//     slug: "real-estate-virtual-tours",
//     client: "Prime Properties",
//     duration: "3 месяца",
//     technologies: ["Three.js", "React", "Node.js", "WebGL", "AWS S3", "WebXR"],
//     challenges: ["Быстрая загрузка 3D-моделей", "Кросс-браузерная совместимость", "Точные измерения в VR"],
//     solutions: ["Оптимизация 3D-моделей", "Progressive Web App", "Точные алгоритмы измерений"],
//     results: ["Увеличение просмотров на 300%", "Сокращение времени сделок на 40%", "Снижение необходимости физических показов на 60%"],
//     createdAt: "2024-11-15",
//     updatedAt: "2024-11-15",
//   },
//   {
//     _id: "18",
//     title: "Food Delivery Optimization",
//     description: "AI-система оптимизации маршрутов доставки еды",
//     fullDescription: "Разработка системы для оптимизации маршрутов курьеров в реальном времени с учетом пробок и погоды.",
//     category: "ai-integration",
//     tags: ["AI", "LOGISTICS", "OPTIMIZATION", "REAL-TIME"],
//     image: "",
//     slug: "food-delivery-optimization",
//     client: "QuickBite Delivery",
//     duration: "4 месяца",
//     technologies: ["Python", "TensorFlow", "Node.js", "React", "Google Maps API", "Redis"],
//     challenges: ["Оптимизация 1000+ маршрутов одновременно", "Учет погодных условий", "Минимизация времени доставки"],
//     solutions: ["Генетические алгоритмы для маршрутов", "Интеграция с погодными API", "Real-time перепланирование"],
//     results: ["Снижение времени доставки на 35%", "Увеличение количества заказов на 50%", "Экономия топлива на 20%"],
//     createdAt: "2024-12-01",
//     updatedAt: "2024-12-01",
//   },
//   {
//     _id: "19",
//     title: "Fitness AI Coach",
//     description: "Приложение для персональных тренировок с ИИ-тренером",
//     fullDescription: "Мобильное приложение с компьютерным зрением для анализа упражнений и создания персонализированных программ тренировок.",
//     category: "software-development",
//     tags: ["AI", "FITNESS", "COMPUTER VISION", "MOBILE"],
//     image: "",
//     slug: "fitness-ai-coach",
//     client: "FitTech Solutions",
//     duration: "5 месяцев",
//     technologies: ["React Native", "TensorFlow Lite", "Node.js", "MongoDB", "WebRTC", "Firebase"],
//     challenges: ["Точное отслеживание позы в реальном времени", "Персонализация для разных уровней подготовки", "Мотивация пользователей"],
//     solutions: ["Pose estimation модели", "Адаптивные программы тренировок", "Геймификация и достижения"],
//     results: ["Улучшение техники выполнения на 80%", "Удержание пользователей на 300% выше рынка", "Средняя оценка 4.9 в магазинах приложений"],
//     createdAt: "2025-01-10",
//     updatedAt: "2025-01-10",
//   },
//   {
//     _id: "20",
//     title: "Hotel Management System",
//     description: "Комплексная система управления отелем",
//     fullDescription: "Разработка системы для управления бронированиями, заселением, обслуживанием номеров и аналитикой отеля.",
//     category: "software-development",
//     tags: ["HOSPITALITY", "MANAGEMENT", "BOOKING", "ANALYTICS"],
//     image: "",
//     slug: "hotel-management-system",
//     client: "Grand Hotel Chain",
//     duration: "6 месяцев",
//     technologies: ["Java Spring Boot", "React", "PostgreSQL", "Redis", "Docker", "Kubernetes"],
//     challenges: ["Интеграция с 10+ сторонними системами", "Поддержка 24/7 без простоев", "Мультиязычность и мультивалютность"],
//     solutions: ["API Gateway для интеграций", "High availability архитектура", "Локализация для 20+ языков"],
//     results: ["Увеличение загрузки номеров на 25%", "Сокращение операционных затрат на 30%", "Улучшение оценки гостей на 1.5 балла"],
//     createdAt: "2025-02-01",
//     updatedAt: "2025-02-01",
//   },
//   {
//     _id: "21",
//     title: "Digital Marketing Analytics",
//     description: "Платформа аналитики digital-маркетинга",
//     fullDescription: "Система для отслеживания эффективности маркетинговых кампаний на всех каналах с AI-рекомендациями.",
//     category: "ai-integration",
//     tags: ["MARKETING", "ANALYTICS", "AI", "DASHBOARD"],
//     image: "",
//     slug: "digital-marketing-analytics",
//     client: "AdTech Solutions",
//     duration: "4 месяца",
//     technologies: ["Python", "React", "PostgreSQL", "Apache Spark", "Machine Learning", "D3.js"],
//     challenges: ["Агрегация данных с 50+ маркетинговых платформ", "Real-time обработка", "Прогнозирование ROI"],
//     solutions: ["Единый data warehouse", "Stream processing", "Predictive models"],
//     results: ["Увеличение ROI на 40%", "Сокращение CAC на 25%", "Автоматизация отчетов на 80%"],
//     createdAt: "2025-02-15",
//     updatedAt: "2025-02-15",
//   },
//   {
//     _id: "22",
//     title: "Warehouse Robotics Control",
//     description: "Система управления роботизированным складом",
//     fullDescription: "Разработка ПО для управления флотом автономных роботов на складе.",
//     category: "devops",
//     tags: ["ROBOTICS", "AUTOMATION", "WAREHOUSE", "AI"],
//     image: "",
//     slug: "warehouse-robotics-control",
//     client: "LogiBot Systems",
//     duration: "8 месяцев",
//     technologies: ["ROS", "Python", "C++", "React", "WebSocket", "Docker"],
//     challenges: ["Координация 100+ роботов", "Избегание коллизий", "Оптимизация маршрутов"],
//     solutions: ["Централизованная система управления", "Алгоритмы предотвращения столкновений", "Динамическое планирование маршрутов"],
//     results: ["Увеличение производительности на 300%", "Снижение ошибок до 0.01%", "Экономия $5M в год"],
//     createdAt: "2025-03-01",
//     updatedAt: "2025-03-01",
//   },
//   {
//     _id: "23",
//     title: "Insurance Claims Automation",
//     description: "Автоматизация обработки страховых случаев",
//     fullDescription: "AI-система для автоматической обработки заявлений о страховых случаях с компьютерным зрением для оценки ущерба.",
//     category: "ai-integration",
//     tags: ["INSURANCE", "AI", "AUTOMATION", "COMPUTER VISION"],
//     image: "",
//     slug: "insurance-claims-automation",
//     client: "InsureTech Corp",
//     duration: "6 месяцев",
//     technologies: ["Python", "FastAPI", "OpenCV", "React", "PostgreSQL", "Docker"],
//     challenges: ["Анализ фотографий повреждений", "Обнаружение мошенничества", "Интеграция с legacy системами"],
//     solutions: ["CV модели для оценки ущерба", "ML модели для обнаружения аномалий", "API для интеграции"],
//     results: ["Сокращение времени обработки с 5 дней до 2 часов", "Выявление мошенничества на 95%", "Экономия $10M в год"],
//     createdAt: "2025-03-15",
//     updatedAt: "2025-03-15",
//   },
//   {
//     _id: "24",
//     title: "Event Management Platform",
//     description: "Платформа для организации масштабных мероприятий",
//     fullDescription: "Комплексная система для планирования, продажи билетов и проведения мероприятий.",
//     category: "software-development",
//     tags: ["EVENTS", "TICKETING", "MANAGEMENT", "MOBILE"],
//     image: "",
//     slug: "event-management-platform",
//     client: "EventPro Global",
//     duration: "5 месяцев",
//     technologies: ["React", "Node.js", "MongoDB", "WebSocket", "Stripe", "Docker"],
//     challenges: ["Продажа 100,000+ билетов за минуты", "Управление очередями", "Навигация на мероприятии"],
//     solutions: ["Микросервисы для масштабирования", "Система управления очередями", "Indoor navigation"],
//     results: ["Проведение 500+ мероприятий", "Продажа 2M+ билетов", "Удовлетворенность организаторов 98%"],
//     createdAt: "2025-04-01",
//     updatedAt: "2025-04-01",
//   },
//   {
//     _id: "25",
//     title: "Agricultural IoT Monitoring",
//     description: "IoT-система мониторинга сельскохозяйственных угодий",
//     fullDescription: "Система датчиков и аналитики для оптимизации полива, удобрения и сбора урожая.",
//     category: "video-surveillance",
//     tags: ["IOT", "AGRICULTURE", "SENSORS", "ANALYTICS"],
//     image: "",
//     slug: "agricultural-iot-monitoring",
//     client: "AgroTech Solutions",
//     duration: "7 месяцев",
//     technologies: ["Python", "MQTT", "React", "PostgreSQL", "Machine Learning", "Docker"],
//     challenges: ["Работа в удаленных районах", "Анализ мультиспектральных снимков", "Прогнозирование урожайности"],
//     solutions: ["LPWAN сети", "AI анализ спутниковых данных", "Predictive models"],
//     results: ["Увеличение урожайности на 30%", "Снижение расхода воды на 40%", "Оптимизация удобрений на 25%"],
//     createdAt: "2025-04-15",
//     updatedAt: "2025-04-15",
//   },
//   {
//     _id: "26",
//     title: "Content Management Platform",
//     description: "Корпоративная система управления контентом",
//     fullDescription: "Разработка CMS для крупных издательств с поддержкой мультимедиа и workflow.",
//     category: "software-development",
//     tags: ["CMS", "CONTENT", "PUBLISHING", "WORKFLOW"],
//     image: "",
//     slug: "content-management-platform",
//     client: "MediaCorp International",
//     duration: "6 месяцев",
//     technologies: ["React", "Node.js", "MongoDB", "AWS S3", "Elasticsearch", "Docker"],
//     challenges: ["Управление 1M+ статей", "Мультиредакторская работа", "Публикация на 100+ сайтах"],
//     solutions: ["Version control для контента", "Collaborative editing", "Headless CMS архитектура"],
//     results: ["Ускорение публикации на 70%", "Снижение ошибок на 90%", "Единая платформа для всех медиа"],
//     createdAt: "2025-05-01",
//     updatedAt: "2025-05-01",
//   },
//   {
//     _id: "27",
//     title: "Smart Parking System",
//     description: "Система умной парковки с датчиками и мобильным приложением",
//     fullDescription: "IoT-решение для мониторинга свободных парковочных мест и онлайн-бронирования.",
//     category: "video-surveillance",
//     tags: ["IOT", "SMART CITY", "PARKING", "MOBILE"],
//     image: "",
//     slug: "smart-parking-system",
//     client: "ParkSmart Solutions",
//     duration: "4 месяца",
//     technologies: ["Node.js", "React Native", "MQTT", "PostgreSQL", "AWS IoT", "Docker"],
//     challenges: ["Точность обнаружения занятых мест", "Работа в подземных паркингах", "Интеграция с платежными системами"],
//     solutions: ["Ультразвуковые датчики", "Bluetooth beacons для навигации", "Интеграция с Stripe и PayPal"],
//     results: ["Увеличение загрузки парковки на 40%", "Сокращение времени поиска места на 70%", "Рост выручки на 60%"],
//     createdAt: "2025-05-15",
//     updatedAt: "2025-05-15",
//   },
//   {
//     _id: "28",
//     title: "HR Recruitment Platform",
//     description: "AI-платформа для автоматизации найма персонала",
//     fullDescription: "Система для поиска, оценки и найма кандидатов с использованием искусственного интеллекта.",
//     category: "ai-integration",
//     tags: ["HR", "RECRUITMENT", "AI", "ASSESSMENT"],
//     image: "",
//     slug: "hr-recruitment-platform",
//     client: "TalentFinders Inc.",
//     duration: "5 месяцев",
//     technologies: ["Python", "FastAPI", "React", "PostgreSQL", "NLP", "Docker"],
//     challenges: ["Анализ 10,000+ резюме ежедневно", "Объективная оценка навыков", "Снижение bias при отборе"],
//     solutions: ["NLP для анализа резюме", "Симуляционные тесты", "Алгоритмы для уменьшения bias"],
//     results: ["Сокращение времени найма на 80%", "Улучшение качества найма на 40%", "Снижение затрат на рекрутинг на 60%"],
//     createdAt: "2025-06-01",
//     updatedAt: "2025-06-01",
//   },
//   {
//     _id: "29",
//     title: "Fleet Management System",
//     description: "Система управления автопарком",
//     fullDescription: "Комплексное решение для отслеживания, обслуживания и оптимизации работы транспортных средств.",
//     category: "web-development",
//     tags: ["FLEET", "LOGISTICS", "GPS", "ANALYTICS"],
//     image: "",
//     slug: "fleet-management-system",
//     client: "TransGlobal Logistics",
//     duration: "6 месяцев",
//     technologies: ["React", "Node.js", "MongoDB", "MQTT", "Mapbox", "Docker"],
//     challenges: ["Отслеживание 5000+ транспортных средств", "Прогнозирование технического обслуживания", "Оптимизация маршрутов"],
//     solutions: ["Real-time GPS tracking", "Predictive maintenance", "Route optimization algorithms"],
//     results: ["Снижение расходов на топливо на 25%", "Увеличение использования парка на 30%", "Сокращение простоев на 40%"],
//     createdAt: "2025-06-15",
//     updatedAt: "2025-06-15",
//   },
//   {
//     _id: "30",
//     title: "Digital Twin Factory",
//     description: "Цифровой двойник производственного предприятия",
//     fullDescription: "Создание виртуальной копии фабрики для симуляции, оптимизации и прогнозирования.",
//     category: "devops",
//     tags: ["DIGITAL TWIN", "MANUFACTURING", "SIMULATION", "IOT"],
//     image: "",
//     slug: "digital-twin-factory",
//     client: "AutoManufacturing Co.",
//     duration: "9 месяцев",
//     technologies: ["Unity", "C#", "Python", "React", "MQTT", "Azure Digital Twins"],
//     challenges: ["Интеграция с 1000+ датчиков", "Real-time симуляция", "Прогнозирование сбоев"],
//     solutions: ["OPC UA для интеграции", "High-performance simulation", "ML для predictive maintenance"],
//     results: ["Снижение времени простоя на 50%", "Увеличение производительности на 25%", "Предотвращение сбоев на 80%"],
//     createdAt: "2025-07-01",
//     updatedAt: "2025-07-01",
//   },
//   {
//     _id: "31",
//     title: "Voice Assistant for Banking",
//     description: "Голосовой ассистент для банковских операций",
//     category: "ai-integration",
//     tags: ["VOICE", "BANKING", "AI", "NLP"],
//     image: "",
//     slug: "voice-assistant-for-banking",
//     client: "VoiceBank Inc.",
//     duration: "5 месяцев",
//     technologies: ["Python", "FastAPI", "React Native", "NLP", "WebSocket"],
//     results: ["Автоматизация 60% звонков", "Удовлетворенность клиентов 95%", "Круглосуточная поддержка"],
//     challenges: ["Распознавание акцентов", "Безопасность операций", "Интеграция с банковскими системами"],
//     solutions: ["Мультиязычные модели", "Голосовая биометрия", "Secure API Gateway"],
//     fullDescription: "Разработка голосового помощника для выполнения банковских операций через голосовые команды.",
//     createdAt: "2025-07-15",
//     updatedAt: "2025-07-15",
//   },
//   {
//     _id: "32",
//     title: "Construction Site Monitoring",
//     description: "Дрон-система мониторинга строительных площадок",
//     category: "video-surveillance",
//     tags: ["DRONES", "CONSTRUCTION", "MONITORING", "AI"],
//     image: "",
//     slug: "construction-site-monitoring",
//     client: "BuildTech Solutions",
//     duration: "4 месяца",
//     technologies: ["Python", "OpenCV", "React", "DJI SDK", "AWS"],
//     results: ["Снижение нарушений безопасности на 70%", "Ускорение строительства на 20%", "Автоматизация инспекций"],
//     challenges: ["Автоматический полет дронов", "Анализ изображений в реальном времени", "Интеграция с BIM"],
//     solutions: ["Автопилот для дронов", "Computer vision модели", "BIM API интеграция"],
//     fullDescription: "Система автоматических дронов для мониторинга прогресса строительства и безопасности.",
//     createdAt: "2025-08-01",
//     updatedAt: "2025-08-01",
//   },
//   {
//     _id: "33",
//     title: "Cryptocurrency Exchange",
//     description: "Высоконагруженная криптобиржа",
//     category: "software-development",
//     tags: ["CRYPTO", "EXCHANGE", "TRADING", "SECURITY"],
//     image: "",
//     slug: "cryptocurrency-exchange",
//     client: "CryptoPro Exchange",
//     duration: "8 месяцев",
//     technologies: ["Go", "React", "PostgreSQL", "Redis", "Kubernetes"],
//     results: ["Обработка 100,000 транзакций в секунду", "Безопасность 100%", "Поддержка 50+ криптовалют"],
//     challenges: ["Низкая задержка", "Защита от атак", "Соответствие регуляциям"],
//     solutions: ["In-memory order book", "Multi-layer security", "KYC/AML интеграция"],
//     fullDescription: "Разработка высокопроизводительной и безопасной платформы для торговли криптовалютами.",
//     createdAt: "2025-08-15",
//     updatedAt: "2025-08-15",
//   },
//   {
//     _id: "34",
//     title: "Waste Management Optimization",
//     description: "AI-система оптимизации сбора мусора",
//     category: "ai-integration",
//     tags: ["AI", "WASTE", "OPTIMIZATION", "IOT"],
//     image: "",
//     slug: "waste-management-optimization",
//     client: "EcoCity Municipal",
//     duration: "6 месяцев",
//     technologies: ["Python", "React", "IoT", "ML", "Docker"],
//     results: ["Сокращение маршрутов на 30%", "Экономия топлива на 25%", "Увеличение переработки на 40%"],
//     challenges: ["Определение заполненности контейнеров", "Оптимизация маршрутов", "Интеграция с городской инфраструктурой"],
//     solutions: ["Умные датчики", "Алгоритмы маршрутизации", "API для интеграции"],
//     fullDescription: "Система для оптимизации маршрутов мусоровозов с использованием датчиков и искусственного интеллекта.",
//     createdAt: "2025-09-01",
//     updatedAt: "2025-09-01",
//   },
//   {
//     _id: "35",
//     title: "Personal Finance Advisor",
//     description: "ИИ-советник по личным финансам",
//     category: "software-development",
//     tags: ["FINTECH", "AI", "MOBILE", "PERSONALIZATION"],
//     image: "",
//     slug: "personal-finance-advisor",
//     client: "MoneySmart App",
//     duration: "5 месяцев",
//     technologies: ["React Native", "Python", "ML", "Firebase", "Docker"],
//     results: ["Увеличение сбережений пользователей на 35%", "1M+ пользователей", "Рейтинг 4.8 в магазинах приложений"],
//     challenges: ["Анализ финансовых привычек", "Персонализация рекомендаций", "Безопасность финансовых данных"],
//     solutions: ["ML для анализа расходов", "Адаптивные рекомендации", "End-to-end шифрование"],
//     fullDescription: "Мобильное приложение с ИИ для анализа расходов и создания персонализированных финансовых планов.",
//     createdAt: "2025-09-15",
//     updatedAt: "2025-09-15",
//   },
//   {
//     _id: "36",
//     title: "Pharmacy Management System",
//     description: "Комплексная система управления аптечной сетью",
//     category: "software-development",
//     tags: ["PHARMACY", "HEALTHCARE", "INVENTORY", "ANALYTICS"],
//     image: "",
//     slug: "pharmacy-management-system",
//     client: "PharmaChain Network",
//     duration: "7 месяцев",
//     technologies: ["Java", "React", "PostgreSQL", "Redis", "Docker"],
//     results: ["Сокращение излишков на 40%", "Автоматизация заказов на 90%", "Снижение ошибок до 0.1%"],
//     challenges: ["Управление сроком годности", "Интеграция с поставщиками", "Соответствие регуляциям"],
//     solutions: ["Автоматическое отслеживание сроков", "EDI интеграция", "Compliance dashboard"],
//     fullDescription: "Система для управления инвентарем, заказами и аналитикой для сети аптек.",
//     createdAt: "2025-10-01",
//     updatedAt: "2025-10-01",
//   },
//   {
//     _id: "37",
//     title: "Sports Analytics Platform",
//     description: "Платформа аналитики для профессиональных спортивных команд",
//     category: "ai-integration",
//     tags: ["SPORTS", "ANALYTICS", "AI", "PERFORMANCE"],
//     image: "",
//     slug: "sports-analytics-platform",
//     client: "ProSports Analytics",
//     duration: "6 месяцев",
//     technologies: ["Python", "React", "PostgreSQL", "ML", "Docker"],
//     results: ["Улучшение результатов команд на 15%", "Снижение травматизма на 30%", "Оптимизация стратегий"],
//     challenges: ["Обработка данных с носимых устройств", "Real-time анализ", "Визуализация сложных данных"],
//     solutions: ["Stream processing", "Real-time ML модели", "Интерактивные дашборды"],
//     fullDescription: "Система для анализа производительности спортсменов и разработки оптимальных стратегий.",
//     createdAt: "2025-10-15",
//     updatedAt: "2025-10-15",
//   },
//   {
//     _id: "38",
//     title: "Language Learning AI",
//     description: "ИИ-платформа для изучения языков",
//     category: "ai-integration",
//     tags: ["EDUCATION", "AI", "LANGUAGE", "MOBILE"],
//     image: "",
//     slug: "language-learning-ai",
//     client: "LinguaTech",
//     duration: "8 месяцев",
//     technologies: ["Python", "React Native", "NLP", "Speech Recognition", "Docker"],
//     results: ["Ускорение изучения на 50%", "2M+ активных пользователей", "Поддержка 20+ языков"],
//     challenges: ["Распознавание акцентов", "Адаптация к уровню ученика", "Мотивация к регулярным занятиям"],
//     solutions: ["Адаптивные модели распознавания", "Personalized learning paths", "Геймификация"],
//     fullDescription: "Приложение для изучения языков с использованием ИИ для персонализации и обратной связи.",
//     createdAt: "2025-11-01",
//     updatedAt: "2025-11-01",
//   },
//   {
//     _id: "39",
//     title: "Car Rental Platform",
//     description: "Платформа для аренды автомобилей с поддержкой blockchain",
//     category: "software-development",
//     tags: ["CAR RENTAL", "BLOCKCHAIN", "MOBILE", "PAYMENTS"],
//     image: "",
//     slug: "car-rental-platform",
//     client: "RentACar Global",
//     duration: "5 месяцев",
//     technologies: ["React Native", "Node.js", "Ethereum", "Smart Contracts", "Docker"],
//     results: ["Снижение мошенничества на 95%", "Автоматизация 90% процессов", "Глобальная экспансия"],
//     challenges: ["Проверка водителей", "Автоматические платежи", "Международные операции"],
//     solutions: ["Blockchain для идентификации", "Smart contracts для платежей", "Мультивалютная поддержка"],
//     fullDescription: "Децентрализованная платформа для аренды автомобилей с использованием blockchain для безопасности и прозрачности.",
//     createdAt: "2025-11-15",
//     updatedAt: "2025-11-15",
//   },
//   {
//     _id: "40",
//     title: "Industrial Predictive Maintenance",
//     description: "Система прогнозирования поломок промышленного оборудования",
//     category: "ai-integration",
//     tags: ["INDUSTRIAL", "PREDICTIVE", "IOT", "MAINTENANCE"],
//     image: "",
//     slug: "industrial-predictive-maintenance",
//     client: "HeavyIndustries Co.",
//     duration: "9 месяцев",
//     technologies: ["Python", "React", "IoT", "ML", "Time Series"],
//     results: ["Снижение простоев на 60%", "Экономия на обслуживании $5M", "Увеличение срока службы оборудования"],
//     challenges: ["Анализ вибрационных данных", "Прогнозирование редких событий", "Интеграция с SCADA"],
//     solutions: ["Signal processing алгоритмы", "Anomaly detection модели", "OPC UA интеграция"],
//     fullDescription: "AI-система для прогнозирования поломок промышленного оборудования на основе данных с датчиков.",
//     createdAt: "2025-12-01",
//     updatedAt: "2025-12-01",
//   },
//   {
//     _id: "41",
//     title: "Mental Health AI Assistant",
//     description: "ИИ-ассистент для поддержки ментального здоровья",
//     category: "ai-integration",
//     tags: ["HEALTH", "AI", "MENTAL", "MOBILE"],
//     image: "",
//     slug: "mental-health-ai-assistant",
//     client: "MindCare Solutions",
//     duration: "7 месяцев",
//     technologies: ["Python", "React Native", "NLP", "ML", "Docker"],
//     results: ["Помощь 500,000+ пользователям", "Снижение симптомов на 40%", "Круглосуточная поддержка"],
//     challenges: ["Эмпатичные ответы", "Кризисные ситуации", "Конфиденциальность"],
//     solutions: ["Empathy models", "Кризисные протоколы", "End-to-end шифрование"],
//     fullDescription: "Мобильное приложение с ИИ для поддержки ментального здоровья и эмоционального благополучия.",
//     createdAt: "2026-01-01",
//     updatedAt: "2026-01-01",
//   },
//   {
//     _id: "42",
//     title: "Smart Home Automation",
//     description: "Комплексная система умного дома",
//     category: "web-development",
//     tags: ["SMART HOME", "IOT", "AUTOMATION", "AI"],
//     image: "",
//     slug: "smart-home-automation",
//     client: "HomeSmart Tech",
//     duration: "6 месяцев",
//     technologies: ["Python", "React", "MQTT", "Node.js", "Docker"],
//     results: ["Экономия энергии на 35%", "Автоматизация 90% процессов", "Интеграция 100+ устройств"],
//     challenges: ["Совместимость устройств", "Безопасность", "Простота управления"],
//     solutions: ["Universal protocol bridge", "Security by design", "Intuitive interface"],
//     fullDescription: "Система для автоматизации и управления всеми устройствами умного дома через единый интерфейс.",
//     createdAt: "2026-01-15",
//     updatedAt: "2026-01-15",
//   },
//   {
//     _id: "43",
//     title: "Fashion AI Stylist",
//     description: "ИИ-стилист для подбора одежды",
//     category: "ai-integration",
//     tags: ["FASHION", "AI", "RECOMMENDATION", "MOBILE"],
//     image: "",
//     slug: "fashion-ai-stylist",
//     client: "StyleAI Tech",
//     duration: "5 месяцев",
//     technologies: ["Python", "React Native", "Computer Vision", "ML", "Docker"],
//     results: ["Увеличение продаж на 45%", "Персонализация для 1M+ пользователей", "Снижение возвратов на 60%"],
//     challenges: ["Анализ стиля", "Рекомендации по сочетаниям", "Интеграция с магазинами"],
//     solutions: ["Style analysis models", "Compatibility algorithms", "E-commerce API"],
//     fullDescription: "Приложение с ИИ для анализа стиля и подбора персонализированных образов одежды.",
//     createdAt: "2026-02-01",
//     updatedAt: "2026-02-01",
//   },
//   {
//     _id: "44",
//     title: "Maritime Logistics Platform",
//     description: "Платформа для оптимизации морских перевозок",
//     category: "software-development",
//     tags: ["LOGISTICS", "MARITIME", "OPTIMIZATION", "AI"],
//     image: "",
//     slug: "maritime-logistics-platform",
//     client: "OceanFreight Global",
//     duration: "8 месяцев",
//     technologies: ["Python", "React", "PostgreSQL", "ML", "Docker"],
//     results: ["Сокращение времени в пути на 20%", "Экономия топлива на 15%", "Оптимизация 1000+ маршрутов"],
//     challenges: ["Прогнозирование погоды", "Планирование портов", "Таможенные процессы"],
//     solutions: ["Weather prediction models", "Port optimization", "Customs automation"],
//     fullDescription: "Система для оптимизации морских грузоперевозок с использованием ИИ и анализа данных.",
//     createdAt: "2026-02-15",
//     updatedAt: "2026-02-15",
//   },
//   {
//     _id: "45",
//     title: "Music Creation AI",
//     description: "ИИ-инструмент для создания музыки",
//     category: "ai-integration",
//     tags: ["MUSIC", "AI", "CREATIVE", "AUDIO"],
//     image: "",
//     slug: "music-creation-ai",
//     client: "SoundAI Studio",
//     duration: "7 месяцев",
//     technologies: ["Python", "React", "TensorFlow", "Audio Processing", "Docker"],
//     results: ["Создание 10,000+ треков", "Автоматизация 70% процессов", "Интеграция с DAW"],
//     challenges: ["Качество генерации", "Стилистическое разнообразие", "Интеграция с профессиональным софтом"],
//     solutions: ["High-quality audio models", "Style transfer", "VST plugin integration"],
//     fullDescription: "Инструмент с ИИ для автоматического создания и аранжировки музыкальных композиций.",
//     createdAt: "2026-03-01",
//     updatedAt: "2026-03-01",
//   },
//   {
//     _id: "46",
//     title: "Virtual Fitness Studio",
//     description: "Виртуальная студия фитнеса с ИИ-тренером",
//     category: "software-development",
//     tags: ["FITNESS", "VR", "AI", "IMMERSIVE"],
//     image: "",
//     slug: "virtual-fitness-studio",
//     client: "FitVR Studios",
//     duration: "6 месяцев",
//     technologies: ["Unity", "C#", "React", "WebXR", "Docker"],
//     results: ["Увеличение вовлеченности на 300%", "Персонализация тренировок", "Глобальная доступность"],
//     challenges: ["Иммерсивный опыт", "Точное отслеживание движений", "Социальные взаимодействия"],
//     solutions: ["High-quality VR", "Motion tracking", "Social VR features"],
//     fullDescription: "VR-платформа для фитнеса с ИИ-тренером и возможностью групповых тренировок.",
//     createdAt: "2026-03-15",
//     updatedAt: "2026-03-15",
//   },
//   {
//     _id: "47",
//     title: "Smart Agriculture Drones",
//     description: "Система дронов для точного земледелия",
//     category: "video-surveillance",
//     tags: ["AGRICULTURE", "DRONES", "AI", "PRECISION"],
//     image: "",
//     slug: "smart-agriculture-drones",
//     client: "AgroDrone Tech",
//     duration: "5 месяцев",
//     technologies: ["Python", "React", "Computer Vision", "DJI SDK", "Docker"],
//     results: ["Увеличение урожайности на 25%", "Снижение расхода удобрений на 30%", "Автоматизация мониторинга"],
//     challenges: ["Автономные полеты", "Анализ мультиспектральных данных", "Интеграция с сельхозтехникой"],
//     solutions: ["Autopilot system", "Multispectral analysis", "Farm equipment API"],
//     fullDescription: "Система автономных дронов для мониторинга и анализа сельскохозяйственных угодий.",
//     createdAt: "2026-04-01",
//     updatedAt: "2026-04-01",
//   },
//   {
//     _id: "48",
//     title: "AI Patent Analyzer",
//     description: "ИИ-система анализа патентов и исследований",
//     category: "ai-integration",
//     tags: ["AI", "PATENTS", "RESEARCH", "ANALYTICS"],
//     image: "",
//     slug: "ai-patent-analyzer",
//     client: "PatentAI Research",
//     duration: "8 месяцев",
//     technologies: ["Python", "React", "NLP", "ML", "Elasticsearch"],
//     results: ["Сокращение времени анализа на 90%", "Выявление трендов", "Предсказание инноваций"],
//     challenges: ["Обработка миллионов документов", "Понимание технического языка", "Выявление связей"],
//     solutions: ["Distributed processing", "Technical NLP models", "Knowledge graph"],
//     fullDescription: "Система с ИИ для анализа патентов и научных исследований для выявления инновационных трендов.",
//     createdAt: "2026-04-15",
//     updatedAt: "2026-04-15",
//   },
//   {
//     _id: "49",
//     title: "Disaster Response System",
//     description: "Система для координации действий при ЧС",
//     category: "web-development",
//     tags: ["DISASTER", "COORDINATION", "IOT", "REAL-TIME"],
//     image: "",
//     slug: "disaster-response-system",
//     client: "EmergencyResponse Gov",
//     duration: "9 месяцев",
//     technologies: ["React", "Node.js", "IoT", "GIS", "Docker"],
//     results: ["Сокращение времени реагирования на 50%", "Координация 1000+ спасателей", "Спасение 10,000+ жизней"],
//     challenges: ["Связь в разрушенных зонах", "Real-time координация", "Интеграция с разными службами"],
//     solutions: ["Mesh сети", "Real-time dashboard", "Unified API"],
//     fullDescription: "Система для координации действий спасательных служб при чрезвычайных ситуациях.",
//     createdAt: "2026-05-01",
//     updatedAt: "2026-05-01",
//   },
//   {
//     _id: "50",
//     title: "Quantum Computing Platform",
//     description: "Платформа для квантовых вычислений и симуляций",
//     category: "software-development",
//     tags: ["QUANTUM", "COMPUTING", "SIMULATION", "RESEARCH"],
//     image: "",
//     slug: "quantum-computing-platform",
//     client: "QuantumTech Research",
//     duration: "12 месяцев",
//     technologies: ["Python", "Qiskit", "React", "Docker", "Kubernetes"],
//     results: ["Ускорение вычислений в 1000 раз", "Симуляция сложных систем", "Прорыв в исследованиях"],
//     challenges: ["Сложность квантовых алгоритмов", "Интеграция с классическими системами", "Визуализация результатов"],
//     solutions: ["Quantum algorithm library", "Hybrid computing", "Advanced visualization"],
//     fullDescription: "Платформа для разработки и выполнения квантовых алгоритмов с интеграцией в классические вычислительные системы.",
//     createdAt: "2026-05-15",
//     updatedAt: "2026-05-15",
//   },
// ];
